version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout

      - run:
          name: Install utilities
          command: |
            apk add xz

      - run:
          name: Get nixpkgs
          command: |
            rev=$(cat rev.txt)
            wget -O nixpkgs.tar.gz https://github.com/dramforever/nixpkgs/archive/$rev.tar.gz
            tar xzf nixpkgs.tar.gz
            mv nixpkgs-$rev nixpkgs

      - run:
          name: Build everything
          command: |
            ./build.sh

      - store_artifacts:
          path: nix-stdenv-installer.tar.xz
          destination: nix-stdenv-installer.tar.xz

      - store_artifacts:
          path: nix-installer.tar.xz
          destination: nix-installer.tar.xz
